language: php

sudo: required

addons:
  firefox: "47.0.1"
  postgresql: "9.4"
  mysql: "8.0.2"
  apt:
    packages:
      - oracle-java9-installer
      - oracle-java9-set-default

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 5.6
 - 7.1
 - 7.2

env:
  - MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli
  - MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli
  - MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli
  - MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_33_STABLE DB=mysqli

matrix:
  exclude:
  - php: 7.1
    env: MOODLE_BRANCH=MOODLE_33_STABLE DB=mysqli
  - php: 7.1
    env: MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql
  - php: 7.2
    env: MOODLE_BRANCH=MOODLE_33_STABLE DB=mysqli
  - php: 7.2
    env: MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
  - php: 7.2
    env: MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli
  - php: 7.2
    env: MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
  - php: 7.2
    env: MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli
  - php: 7.2
    env: MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql
  - php: 7.1
    env: MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli
  - php: 7.1
    env: MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install node
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
  - moodle-plugin-ci phpunit --coverage-text