language: php

# We use trusty as currently there is an issue with java and moodle-plugin-ci mustache linting which
# causes causes tests to fail on xenial and bionic. (See https://github.com/blackboard-open-source/moodle-plugin-ci/issues/91).
dist: trusty

sudo: true

addons:
  firefox: "47.0.1"
  postgresql: "9.5"
  apt:
    packages:
      - openjdk-8-jre-headless

services: mysql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.1
 - 7.2
 - 7.3

matrix:
  exclude:
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_39_STABLE DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_39_STABLE DB=pgsql
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_39_STABLE DB=mysqli
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_39_STABLE DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_38_STABLE DB=mysqli
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_38_STABLE DB=pgsql
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_38_STABLE DB=mysqli
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_38_STABLE DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql

env:
  global:
    - IGNORE_NAMES=mobile_*.mustache
  matrix:
    - MOODLE_BRANCH=MOODLE_39_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_39_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_38_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_38_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 14.0
  - nvm use 14.0
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  # moodle-plugin-ci phpdoc
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
